name: Patcher

on:
  push:
    branches: [ "v*" ]
    paths: [ "patcher/**/*" ]
  pull_request:
    branches: [ "v*" ]
    paths: [ "patcher/**/*" ]

env:
  DOTNET_VERSION: 8.x

jobs:
  build:
    name: Build Patcher
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build Patcher
        run: |
          export DOTNET_NOLOGO=true
          export DOTNET_CLI_TELEMETRY_OPTOUT=true
          dotnet publish patcher/HitmanPatcher.CLI/HitmanPatcher.CLI.csproj -r win-x64 -c Release -p:PublishTrimmed=True -p:PublishSingleFile=True --self-contained -p DebugType=none -p:EnableWindowsTargeting=True --nologo -o patcher/Publish/Windows-x64
          dotnet publish patcher/HitmanPatcher.CLI/HitmanPatcher.CLI.csproj -r linux-x64 -c Release -p:PublishTrimmed=True -p:PublishSingleFile=True --self-contained -p DebugType=none --nologo -o patcher/Publish/Linux-x64
          dotnet publish patcher/HitmanPatcher.UI/HitmanPatcher.UI.csproj -r win-x64 -c Release -p:PublishSingleFile=True --self-contained -p DebugType=none -p:EnableWindowsTargeting=True --nologo -o patcher/Publish/Windows-x64

      - name: Upload patcher-windows-cli
        uses: actions/upload-artifact@v4
        with:
          name: patcher-windows-cli
          path: patcher/Publish/Windows-x64/PeacockPatcher.CLI.exe

      - name: Upload patcher-windows-ui
        uses: actions/upload-artifact@v4
        with:
          name: patcher-windows-ui
          path: patcher/Publish/Windows-x64/PeacockPatcher.UI.exe

      - name: Upload patcher-linux-cli
        uses: actions/upload-artifact@v4
        with:
          name: patcher-linux-cli
          path: patcher/Publish/Linux-x64/PeacockPatcher.CLI.exe
